### PR TITLE
Minor updates to SOFA-HD and QLSOFA-HD to fix LVS test

### PR DESCRIPTION
**Pull request by ganeshgore**
Note: PostPNR netlist not changed so no need to run function verification

### CODE REVIEW

**Review by tangxifan — APPROVED** [review]

**Comment by tangxifan** [comment]
Can you update the `install_dependency.sh` and make it synchronized with OpenFPGA upstream updates? It should make the CI pass

**Comment by ganeshgore** [comment]
I made couple of changes that doesn't seems to fix test. You fix it on master I will merge master.

**Comment by tangxifan** [comment]
Just realize that OpenFPGA now contains a submodule, should enable it checking it out.
https://github.com/lnis-uofu/OpenFPGA/blob/6b15ae6805d8c420ad9ad336e2b286d88df6677f/.github/workflows/build.yml#L126

**Comment by ganeshgore** [comment]
Make change on the master I will merge

**Pull request merged**
