### PR TITLE
(1)CFG_DONE to add is_config_enable(2)reset default=1 under tile_anno…

### PR DESCRIPTION
**Pull request by liaokevin-ql**
two changes for Rakesh's issues,
(1) to let testbench drive CFG_DONE, CFG_DONE[0] = config_done[0];
(2) to correct "reset" polarity in testbench, reset[0] = ~greset[0];

### CODE REVIEW

**Comment by tangxifan** [comment]
Hi Kevin,
   It is due to something wrong when we bumped up the Yosys version in OpenFPGA. @lnsharma reported the same issue a few days ago and we are looking into the problem.

**Comment by liaokevin-ql** [comment]
Is Yosys issue fixed? This PR is till pending for reviewer to merge.

**Comment by tangxifan** [comment]
@liaokevin-ql The issue has been fixed. You just need to merge master to your local branch. it should work well

**Comment by liaokevin-ql** [comment]
Hi Xifan,
Below is a snapshot where I did “git merge origin”. I also add comment to explain this merge.
What is the next step ?
Regards,
Kevin

[cid:image002.png@01D6FA6B.C74FD1B0]

**Comment by liaokevin-ql** [comment]
With advise from Lalit. I followed with "git puch origin".
Thanks all.

**Review by tpagarani — APPROVED** [review]
LGTM. CI is also passing. I will go ahead and merge it.

**Pull request merged**
